const assert = require("node:assert/strict");
const C = require("../src/core.js");
const f = C.frame("P1,GET");
assert.equal(C.verify(f), true);
assert.equal(C.verify(f.replace(/C....#$/, "C0000#")), false);
const parser = new C.StreamParser();
assert.deepEqual(parser.feed("junk$OK#$OK#tail"), ["$OK#", "$OK#"]);
assert.deepEqual(parser.feed("$T1,F,"), []);
assert.deepEqual(parser.feed("123#"), ["$T1,F,123#"]);
const pid = { AP: 96, AD: 48, VP: 62, VI: 31, TP: 17, TD: 20 };
assert.match(C.manualSet(pid), /^\$P1,MSET,96\.00,48\.00,62\.00,31\.00,17\.00,20\.00,C[0-9A-F]{4}#$/);
assert.match(C.legacyMotion(1, 0, pid), /^\$1,0,0,0,0,0,0,AP96\.00/);
const ps = C.parsePidStatus(C.frame("P1,PID,96.00,48.00,62.00,31.00,17.00,20.00,0,1,1"));
assert.equal(ps.pid.AP, 96); assert.equal(ps.trainingLocked, true); assert.equal(ps.balanceStarted, true);
const fast = C.parseFast(C.frame("T1,F,200,A1.25,G-3.0,EL4,ER5,ML6,MR7,S0,L1,R1,C10,C20,C30,C40"));
assert.equal(fast.angle, 1.25); assert.equal(fast.trainingLocked, true); assert.equal(fast.c4, 0);
const m = C.metrics([fast, { ...fast, angle: -1.25, gyro: 3 }]); assert.equal(m.samples, 2); assert.equal(m.peakAngle, 1.25);
const proposal = C.harness(pid, { peakAngle: 9, rmsGyro: 21 });
assert.equal(C.validateProposal(proposal, pid, 5).decision, "propose");
assert.throws(() => C.validateProposal({ ...proposal, candidate: { ...proposal.candidate, VP: 63 } }, pid, 5));
console.log("Route A Bluefy core tests: PASS");
