"""Export the deterministic PPO actor used by the STM32 TEST mode.

The generated C module contains only the policy network.  The PPO critic,
optimizer state, action distribution variance and Python runtime are not
needed for deterministic inference on the microcontroller.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

import numpy as np
from stable_baselines3 import PPO


KEYS = (
    "mlp_extractor.policy_net.0.weight",
    "mlp_extractor.policy_net.0.bias",
    "mlp_extractor.policy_net.2.weight",
    "mlp_extractor.policy_net.2.bias",
    "action_net.weight",
    "action_net.bias",
)


def _c_float(value: float) -> str:
    text = f"{float(np.float32(value)):.9g}"
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return text + "f"


def _array(name: str, values: np.ndarray, columns: int = 8) -> str:
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    rows = []
    for start in range(0, flat.size, columns):
        chunk = ", ".join(_c_float(v) for v in flat[start : start + columns])
        rows.append(f"    {chunk}")
    body = ",\n".join(rows)
    return f"static const float {name}[{flat.size}] = {{\n{body}\n}};\n"


def export_actor(model_path: Path, output_path: Path) -> None:
    model = PPO.load(model_path, device="cpu")
    state = model.policy.state_dict()
    arrays = [state[key].detach().cpu().numpy() for key in KEYS]
    expected = ((32, 13), (32,), (32, 32), (32,), (2, 32), (2,))
    actual = tuple(array.shape for array in arrays)
    if actual != expected:
        raise RuntimeError(f"unexpected actor layout: {actual!r}")

    digest = hashlib.sha256(model_path.read_bytes()).hexdigest()
    names = ("actor_w0", "actor_b0", "actor_w1", "actor_b1", "actor_w2", "actor_b2")
    blocks = "\n".join(_array(name, value) for name, value in zip(names, arrays))
    source = f'''/* Generated by tools/export_neural_actor.py.
 * Source model SHA-256: {digest}
 * Layout: 13 -> ReLU(32) -> ReLU(32) -> 2, deterministic mean action.
 */
#include "neural_actor.h"

{blocks}
static float actor_clip(float value, float minimum, float maximum)
{{
    if (value < minimum) return minimum;
    if (value > maximum) return maximum;
    return value;
}}

void NeuralActor_Init(void)
{{
    /* The actor is stateless and all parameters reside in read-only Flash. */
}}

void NeuralActor_Predict(const float input[NEURAL_ACTOR_INPUTS],
                         float output[NEURAL_ACTOR_OUTPUTS])
{{
    float hidden0[NEURAL_ACTOR_HIDDEN];
    float hidden1[NEURAL_ACTOR_HIDDEN];
    float sum;
    int i;
    int j;

    for (i = 0; i < NEURAL_ACTOR_HIDDEN; ++i)
    {{
        sum = actor_b0[i];
        for (j = 0; j < NEURAL_ACTOR_INPUTS; ++j)
        {{
            sum += actor_w0[i * NEURAL_ACTOR_INPUTS + j] * input[j];
        }}
        hidden0[i] = (sum > 0.0f) ? sum : 0.0f;
    }}

    for (i = 0; i < NEURAL_ACTOR_HIDDEN; ++i)
    {{
        sum = actor_b1[i];
        for (j = 0; j < NEURAL_ACTOR_HIDDEN; ++j)
        {{
            sum += actor_w1[i * NEURAL_ACTOR_HIDDEN + j] * hidden0[j];
        }}
        hidden1[i] = (sum > 0.0f) ? sum : 0.0f;
    }}

    for (i = 0; i < NEURAL_ACTOR_OUTPUTS; ++i)
    {{
        sum = actor_b2[i];
        for (j = 0; j < NEURAL_ACTOR_HIDDEN; ++j)
        {{
            sum += actor_w2[i * NEURAL_ACTOR_HIDDEN + j] * hidden1[j];
        }}
        output[i] = actor_clip(sum, -1.0f, 1.0f);
    }}
}}
'''
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8", newline="\n")
    print(f"exported {sum(array.size for array in arrays)} actor parameters to {output_path}")
    print(f"source model sha256={digest}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    export_actor(args.model.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
