"""Quantise a checkpoint into policy_weights_q.h for the fixed-point inference
(policy_q.c) the team's STM32 build uses: int16 weights with one float scale
per output row, inputs in Q16.16, tanh evaluated in Q12 -> Q15.

Reconstructed from policy_q.c's number formats and checked against the team's
own generated header for run 7: identical integer weights and scales (see
--check). For each layer, with per-row scale s = max|W[o,:]| / 32767:

    layer 0  x in Q16.16:  pre_Q12 = acc * (s / 16)    + b * 4096
    layer 1  x in Q15:     pre_Q12 = acc * (s / 8)     + b * 4096
    layer 2  x in Q15:     action  = acc * (s / 32768) + b

    python firmware/quantize_weights.py [--model path.zip] [--out firmware/policy_weights_q.h]
    python firmware/quantize_weights.py --check path/to/their/policy_weights_q.h --model <same checkpoint>
"""
import argparse
import re
from pathlib import Path

import numpy as np
from stable_baselines3 import PPO


def layers(model_path):
    sd = PPO.load(model_path, device="cpu").policy.state_dict()
    return [(sd["mlp_extractor.policy_net.0.weight"].numpy(), sd["mlp_extractor.policy_net.0.bias"].numpy(), 16.0, 4096.0),
            (sd["mlp_extractor.policy_net.2.weight"].numpy(), sd["mlp_extractor.policy_net.2.bias"].numpy(), 8.0, 4096.0),
            (sd["action_net.weight"].numpy(), sd["action_net.bias"].numpy(), 32768.0, 1.0)]


def quantise(model_path):
    # float32 throughout: that is what reproduces the team's header bit for
    # bit (float64 rounds 2 of run 7's 4096 layer-1 weights the other way).
    out = []
    for w, b, kdiv, cmul in layers(model_path):
        w = w.astype(np.float32)
        s = (np.abs(w).max(axis=1) / np.float32(32767.0)).astype(np.float32)
        q = np.rint(w / s[:, None]).astype(np.int64)
        out.append((q, (s.astype(np.float64) / kdiv).astype(np.float32),
                    (b.astype(np.float64) * cmul).astype(np.float32),
                    float(np.abs(q * s[:, None].astype(np.float64) - w).max())))
    return out


def write(model_path, out_path):
    qs = quantise(model_path)
    worst = max(x[3] for x in qs)
    (q0, _, _, _), (q1, _, _, _), (q2, _, _, _) = qs
    def ints(name, a):
        f = a.ravel()
        rows = ",\n".join("    " + ", ".join(f"{v:6d}" for v in f[i:i + 12]) for i in range(0, f.size, 12))
        return f"static const int16_t {name}[{f.size}] = {{\n{rows}\n}};\n"
    def floats(name, a):
        rows = ",\n".join("    " + ", ".join(f"{v:+.9e}f" for v in a[i:i + 4]) for i in range(0, a.size, 4))
        return f"static const float {name}[{a.size}] = {{\n{rows}\n}};\n"
    n_obs, n_h1, n_h2, n_act = q0.shape[1], q0.shape[0], q1.shape[0], q2.shape[0]
    txt = ("/* Auto-generated by firmware/quantize_weights.py - do not edit by hand.\n"
           f" * Source checkpoint: {model_path}\n"
           f" * Network: {n_obs} -> {n_h1} -> {n_h2} -> {n_act}, int16 weights, per-row scale\n"
           f" * Worst weight rounding error: {worst:.3e}\n */\n"
           "#ifndef POLICY_WEIGHTS_Q_H\n#define POLICY_WEIGHTS_Q_H\n\n#include <stdint.h>\n\n"
           f"#define POLICY_Q_N_OBS {n_obs}\n#define POLICY_Q_N_H1  {n_h1}\n#define POLICY_Q_N_H2  {n_h2}\n"
           f"#define POLICY_Q_N_ACT {n_act}\n#define POLICY_Q_IN_FRAC  16\n#define POLICY_Q_H_FRAC   15\n"
           "#define POLICY_Q_T_FRAC   12\n\n")
    for i, (q, k, c, _) in enumerate(qs):
        txt += ints(f"policy_q_w{i}", q) + "\n"
    for i, (q, k, c, _) in enumerate(qs):
        txt += floats(f"policy_q_k{i}", k) + "\n" + floats(f"policy_q_c{i}", c) + "\n"
    txt += "#endif /* POLICY_WEIGHTS_Q_H */\n"
    Path(out_path).write_text(txt)
    print(f"wrote {out_path}  ({n_obs}->{n_h1}->{n_h2}->{n_act}, worst rounding {worst:.3e})")


def check(model_path, header_path):
    src = Path(header_path).read_text()
    def arr(name):
        body = re.search(rf"{name}\[\d+\]\s*=\s*\{{(.*?)\}};", src, re.S).group(1)
        return np.array([float(x.rstrip('f')) for x in re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?f?", body)])
    ok = True
    for i, (q, k, c, _) in enumerate(quantise(model_path)):
        dq = np.abs(arr(f"policy_q_w{i}") - q.ravel()).max()
        dk = np.abs(arr(f"policy_q_k{i}") / k - 1).max()
        dc = np.abs(arr(f"policy_q_c{i}") - c).max()
        print(f"layer {i}: max int weight diff {dq:.0f}, max scale rel diff {dk:.1e}, max bias diff {dc:.1e}")
        ok &= dq == 0 and dk < 1e-6 and dc < 1e-3
    print("MATCH" if ok else "MISMATCH")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", default="models/best_real/best_model.zip")
    ap.add_argument("--out", default="firmware/policy_weights_q.h")
    ap.add_argument("--check", metavar="HEADER")
    a = ap.parse_args()
    check(a.model, a.check) if a.check else write(a.model, a.out)
